### ISSUE TITLE
MapStory/StoryLayer migration plan

### ISSUE THREAD

**Issue by ischneider** [MapStory/story-tools#204]
ordered sub-tasks

- [x] take transform out of MapConfig #199 
- [x] immutable storymap/storylayer classes #200
- [x] storymap from config #201
- [x] viewer example #202
- [x] editable storymap/storylayer classes #203
